version: '3.8'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/dev_data
    ports:
      - 5431:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/cardealer
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres_data:
