version: '3.8'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/dev_data
    ports:
      - 5431:5432

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 app.wsgi
    ports:
      - "8000"
    volumes:
      - .:/cardealer
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379

  celery:
    restart: always
    build:
      context: .
    command: celery -A app.celery worker --loglevel=INFO
    volumes:
      - .:/cardealer
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

  celery-beat:
    build:
      context: .
    command: celery -A app.celery beat -l info
    volumes:
      - .:/cardealer
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - web


volumes:
  postgres_data: