# Generated by Django 4.2 on 2023-04-28 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="showroomcars",
            name="price_with_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
