# Generated by Django 4.2 on 2023-04-07 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carshowroomdiscount",
            old_name="shop",
            new_name="showroom",
        ),
        migrations.RenameField(
            model_name="carshowroomsaleshistory",
            old_name="shop",
            new_name="showroom",
        ),
        migrations.RenameField(
            model_name="providerdiscount",
            old_name="shops",
            new_name="showrooms",
        ),
        migrations.RenameField(
            model_name="providersaleshistory",
            old_name="shop",
            new_name="showroom",
        ),
        migrations.RenameField(
            model_name="showroomcars",
            old_name="shop",
            new_name="showroom",
        ),
    ]
