# Generated by Django 4.2 on 2023-04-10 10:33

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_shop_carshowroomdiscount_showroom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carshowroomdiscount",
            name="date_end",
            field=models.DateField(
                default=models.DateField(default=datetime.date.today)
            ),
        ),
        migrations.AlterField(
            model_name="carshowroomdiscount",
            name="date_start",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="carshowroomdiscount",
            name="percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="providerdiscount",
            name="date_end",
            field=models.DateField(
                default=models.DateField(default=datetime.date.today)
            ),
        ),
        migrations.AlterField(
            model_name="providerdiscount",
            name="date_start",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="providerdiscount",
            name="percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
