# Generated by Django 4.2 on 2023-04-28 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_showroomcars_price_with_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="providercars",
            name="price_with_discount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="showroomcars",
            name="price_with_discount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
