# Generated by Django 4.2 on 2023-04-11 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_carshowroomdiscount_date_end_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="offer",
            new_name="specification",
        ),
        migrations.AlterField(
            model_name="customer",
            name="age",
            field=models.IntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(18)]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="car",
            unique_together={("brand", "model", "color", "engine_v", "engine_t")},
        ),
    ]
