# Generated by Django 4.2 on 2023-04-13 13:03

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_carshowroom_specification_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="engine_t",
            new_name="engine_type",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="engine_v",
            new_name="engine_volume",
        ),
        migrations.RemoveField(
            model_name="carshowroomdiscount",
            name="cars",
        ),
        migrations.RemoveField(
            model_name="providerdiscount",
            name="cars",
        ),
        migrations.RemoveField(
            model_name="providerdiscount",
            name="showrooms",
        ),
        migrations.AddField(
            model_name="carshowroomdiscount",
            name="params",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
            ),
        ),
        migrations.AddField(
            model_name="providerdiscount",
            name="params",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="car",
            unique_together={
                ("brand", "model", "color", "engine_volume", "engine_type")
            },
        ),
    ]
