# Generated by Django 4.2 on 2023-04-14 08:21

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_engine_t_car_engine_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carshowroom",
            name="specification",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
            ),
        ),
    ]
