# Generated by Django 4.2 on 2023-04-14 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_carshowroom_specification"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="showroomcars",
            unique_together={("car", "showroom")},
        ),
    ]
