# Generated by Django 4.2 on 2023-04-14 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_showroomcars_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="providercars",
            unique_together={("car", "provider")},
        ),
    ]
